postgresql:
CREATE TABLE  test (id SERIAL PRIMARY KEY, username VARCHAR(100) NOT NULL, email VARCHAR(100) UNIQUE NOT NULL);

mssql:
CREATE TABLE test (id INT IDENTITY CONSTRAINT PK_test PRIMARY KEY, username NVARCHAR(100) NOT NULL, email NVARCHAR(100) NOT NULL CONSTRAINT AK_email UNIQUE)
